instances = 2

Vagrant.configure(2) do |config|
    instances.times do |i|
        instance_name = "coreos-#{i}"
        config.vm.define instance_name do |instance|
            instance.vm.box = "yungsang/coreos"

            instance.vm.provider "virtualbox" do |v|
                v.name = instance_name
                v.memory = 630
            end

            instance.vm.network "forwarded_port", guest: 5000, host: 5000 + i
            instance.vm.network "forwarded_port", guest: 3000, host: 3000 + i
            instance.vm.network "private_network", type: "dhcp"

            instance.vm.synced_folder "docker-app", "/docker-app"

            instance.vm.provision "docker" do |d|
                d.build_image "/docker-app", args: "-t 'example-app'"
            end

            instance.vm.provision "file", source: "configs/cloud.config", destination: "/tmp/vagrantfile-user-data"
            instance.vm.provision "shell", inline: "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/"

            instance.vm.provision "shell", inline: "install -m 755 -d /etc/fleet-services/"
            instance.vm.provision "file", source: "services/", destination: "/tmp/"
            instance.vm.provision "shell", inline: "cp /tmp/services/* /etc/fleet-services/"
            instance.vm.provision "shell", inline: "rm -rf /tmp/services/"
        end
    end
end
