Vagrant.configure(2) do |config|
    config.vm.box = "yungsang/coreos"

    config.vm.provider "virtualbox" do |v|
        v.name = "coreos-example"
        v.memory = 1024
    end

    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.synced_folder "docker-app", "/docker-app"

    config.vm.provision "docker" do |d|
        d.build_image "/docker-app",
          args: "-t 'example-app'"
    end
    config.vm.provision "file", source: "services/example-app.service", destination: "/etc/systemd/system/example-app.service"
    config.vm.provision "shell", inline: "systemctl start example-app.service"
end

