Vagrant.configure(2) do |config|
    config.vm.box = "yungsang/coreos"

    config.vm.provider "virtualbox" do |v|
        v.name = "coreos-example"
        v.memory = 1024
    end

    config.vm.provision "file", source: "services/hello.service", destination: "/etc/systemd/system/hello.service"
end

